<?php

/**
 * This file was generated by DAMB
 *
 * @copyright   Copyright (c) 2019 - 2020, AXeL-dev
 * @license     GPL
 * @link        https://github.com/AXeL-dev/damb
 */

// Load DolibarrModules class
include_once DOL_DOCUMENT_ROOT.'/core/modules/DolibarrModules.class.php';

// Load module lib
dol_include_once('streamaccount/lib/module.lib.php');

/**
 * Class to describe and enable module
 */
class modStreamAccount extends DolibarrModules
{
    /**
     * Constructor. Define names, constants, directories, boxes, permissions
     *
     * @param      DoliDB      $db      Database handler
     */
    public function __construct($db)
    {
        // Module configuration
        $this->db              = $db;
        $this->editor_name     = 'SuperAdmin';
        $this->editor_url      = '#';
        $this->numero          = 910001;
        $this->rights_class    = 'streamaccount';
        $this->family          = 'other';
        $this->module_position = 500;
        $this->name            = preg_replace('/^mod/i', '', get_class($this));
        $this->description     = 'Stream AccountDescription';
        $this->picto           = 'streamaccount.png@streamaccount';
        $this->version         = '1.0.0';
        $this->const_name      = get_constant_name($this);
        $this->special         = 0;

        // Module parts (css, js, ...)
        $this->module_parts    = array(
            'css'   => array(),
            'js'    => array(),
            'hooks' => array('externalaccess'),
            'triggers' => 1,
        );

        // Config page
        $this->config_page_url = array('setup.php@streamaccount');

        // Dependencies
        $this->need_dolibarr_version = array(3, 8);
        $this->phpmin                = array(4, 0);
        $this->depends               = array();
        $this->requiredby            = array();
        $this->conflictwith          = array();
        $this->langfiles             = array('streamaccount@streamaccount');

        // Menus
        // $top_menu = 'streamaccount';
        // add_top_menu($this, $top_menu, 'Stream Account', '/streamaccount/index.php');
        // add_left_menu($this, $top_menu, 'streamaccountmenu', 'Index', '/streamaccount/index.php');
        // add_left_submenu($this, $top_menu, 'streamaccountmenu', 'streamaccountnew', 'New', '/streamaccount/card.php?action=create');
        // add_left_submenu($this, $top_menu, 'streamaccountmenu', 'streamaccountlist', 'List', '/streamaccount/list.php');

        // Permissions
        // add_permission($this, 'read', 'ReadPermission', 'r');
        // add_permission($this, 'create', 'CreatePermission', 'c');
        // add_permission($this, 'modify', 'ModifyPermission', 'm');
        // add_permission($this, 'delete', 'DeletePermission', 'd');
    }

    /**
     * Function called when module is enabled.
     * The init function add constants, boxes, permissions and menus
     * (defined in constructor) into Dolibarr database.
     * It also creates data directories
     *
     * @param string $options Options when enabling module ('', 'noboxes')
     * @return int 1 if OK, 0 if KO
     */
    public function init($options = '')
    {
        // Load module tables
        $result = $this->_load_tables('/streamaccount/sql/');

        return $this->_init(array(), $options);
    }

    /**
     * Function called when module is disabled.
     * Remove from database constants, boxes and permissions from Dolibarr database.
     * Data directories are not deleted
     *
     * @param string $options Options when enabling module ('', 'noboxes')
     * @return int 1 if OK, 0 if KO
     */
    public function remove($options = '')
    {
        return $this->_remove(array(), $options);
    }
}
