<?php

/**
 * This file was generated by DAMB
 *
 * @copyright   Copyright (c) 2019 - 2020, AXeL-dev
 * @license     GPL
 * @link        https://github.com/AXeL-dev/damb
 */

/**
 * Print admin page(s) tabs
 * 
 * @param  string $active Active tab title
 */

function print_admin_tabs($active = 'Setup')
{
    $tabs = array(
        array('title' => 'Setup', 'url' => 'streamaccount/admin/setup.php?mainmenu=home'),
        array('title' => 'Changelog', 'url' => 'streamaccount/admin/changelog.php?mainmenu=home'),
        array('title' => 'About', 'url' => 'streamaccount/admin/about.php?mainmenu=home')
    );

    foreach ($tabs as $key => $tab)
    {
        if ($tab['title'] == $active) {
            $tabs[$key]['active'] = true;
            break;
        }
    }

    print_tabs($tabs, 'Stream Account', 'streamaccount.png@streamaccount', -1);
}
function print_clientForm($userid){
     global $langs, $db, $conf;
    $context = Context::getInstance();
   	include $context->clientTplPath.'/clientinfos.tpl.php';
    
}
function print_costumerOrder($userid){
     global $langs, $db, $conf;
    $context = Context::getInstance();    
	include $context->clientTplPath.'/costumerorder.tpl.php';    
}
function print_clientTable($userid){
     global $langs, $db, $conf;
    $context = Context::getInstance();    
    dol_include_once('compta/societe/class/societe.class.php');    
    $langs->load('company');
    
    
    $sql = 'SELECT s.rowid as socid,s.nom as name,s.email,s.phone,s.status as socstatus ';
    $sql.= ' FROM `'.MAIN_DB_PREFIX.'societe` s';
    $sql.= ' INNER JOIN `'.MAIN_DB_PREFIX.'societe_commerciaux` sc ON sc.fk_soc=s.rowid';
    //$sql.= ' INNER JOIN `'.MAIN_DB_PREFIX.'user` u ON sc.fk_soc=s.rowid';
    $sql.= ' WHERE sc.fk_user = '. intval($userid);
    //$sql.= ' AND fk_statut > 0';
    $sql.= ' ORDER BY s.nom DESC';
    
    $tableItems = $context->dbTool->executeS($sql);
    print $db->lasterror;
    
    if(!empty($tableItems))
    {      
        
        print '<table id="client-list" class="table table-striped" >';
        
        print '<thead>';
        
        print '<tr>';
        print ' <th class="text-center" >'.$langs->trans('Name').'</th>';
        print ' <th class="text-center" >'.$langs->trans('Phone').'</th>';
        print ' <th class="text-center" >'.$langs->trans('Email').'</th>';
        print ' <th class="text-center" >'.$langs->trans('Status').'</th>';
        print ' <th class="text-center" ></th>';
        print '</tr>';
        
        print '</thead>';
        
        print '<tbody>';
        $object=new Societe($db);
        foreach ($tableItems as $item)
        {
           
            $dowloadUrl = $context->getRootUrl().'script/interface.php?action=downloadInvoice&id='.$object->id;
           
            if(true){
                $viewLink = $item->name;
                $downloadLink =  $langs->trans('DocumentFileNotAvailable');
            }
            
            $object->status=$item->socstatus;
            print '<tr >';
            print ' <td data-search="'.$item->name.'" data-order="'.$item->name.'" >'.$viewLink.'</td>';
            print ' <td data-search="'.$item->phone.'" data-order="'.$item->phone.'"  >'.$item->phone.'</td>';
            print ' <td data-order="'.$item->email.'"  >'.$item->email.'</td>';
            print ' <td  >'.$object->getLibStatut(0).'</td>'; 
            print ' <td  class="text-right" >'.$downloadLink.'</td>';
            print '</tr>';
            
        }
        print '</tbody>';
        
        print '</table>';
        $jsonUrl = $context->getRootUrl().'script/interface.php?action=getInvoicesList';
    ?>
    <script type="text/javascript" >
     $(document).ready(function(){
         $("#client-list").DataTable({
             "language": {
                 "url": "<?php print $context->getRootUrl(); ?>vendor/data-tables/spanish.json"
             },

             responsive: true,
             columnDefs: [{
                 orderable: false,
                 "aTargets": [-1]
             },{
                 "bSearchable": false,
                 "aTargets": [-1, -2]
             }]
         });
     });
    </script>
    <?php 
    }
    else {
        print '<div class="info clearboth text-center" >';
        print  $langs->trans('EACCESS_Nothing');
        print '</div>';
    }

}
function ulist_soc($userid=0,$socid=0){
    global $langs, $db, $conf;
    $context = Context::getInstance();    
    dol_include_once('compta/societe/class/societe.class.php');    
    $langs->load('company');
    
    $sql = 'SELECT s.rowid as socid,s.nom as name,s.name_alias as alias,s.email,s.phone,s.status as socstatus ';
    $sql.= ' FROM `'.MAIN_DB_PREFIX.'societe` s';
    $sql.= ' INNER JOIN `'.MAIN_DB_PREFIX.'societe_commerciaux` sc ON sc.fk_soc=s.rowid';
    $sql.= ' WHERE sc.fk_user = '. intval($userid);
    $sql.= ' AND s.status > 0';
    $sql.= ' ORDER BY s.nom DESC LIMIT 10';
    
    $tableItems = $context->dbTool->executeS($sql);
    print $db->lasterror;
    
        
    $html='<div class="input-group md-form form-sm form-1 pl-0">
            <div class="input-group-prepend">
                <span class="input-group-text cyan lighten-2" id="basic-text1"><i class="fa fa-search text-white"
                aria-hidden="true"></i></span>
            </div>
            <input class="form-control my-0 py-1" type="text" placeholder="Search" aria-label="Search">
        </div><br>
    <div class="list-group">';
   // var_dump($tableItems);
     if(!empty($tableItems))
    {
         foreach ($tableItems as $item)
        {
            $html.='<a  href="'.$context->getRootUrl('costumerorder','&step=2&socid='.$item->socid).'" class="list-group-item list-group-item-action '.($item->socid===$socid?'active':'').' ">';
            $html.=$item->name;
            if(!empty($item->alias))
            $html.=' ('.$item->alias.')';
            $html.='</a>';
        }
    }
    $html.='</div>';
    return $html;
}
function ulist_stock($warehouseid=0,$prodid=0,$lines=array()){
     global $langs, $db, $conf;
    $context = Context::getInstance();    
    dol_include_once('compta/societe/class/societe.class.php');    
    $langs->load('company');
    $soc=new Societe($db);
    $soc->fetch($_SESSION['socid']);
    
    $sql="SELECT m.fk_product as id, p.ref, p.label,sum(m.value) as stock";
    $sql.=" FROM  llx_product as p";
    $sql.=" LEFT JOIN llx_stock_mouvement  m ON m.fk_product = p.rowid";
    $sql.=" WHERE m.fk_product = p.rowid AND m.fk_entrepot = $warehouseid AND p.entity IN ($conf->entity)";
    $sql.=" GROUP BY m.fk_product";
    $sql.=" ORDER BY p.ref DESC";
    $products = $context->dbTool->executeS($sql);
   //print "PROD_ERR: ".$db->lasterror.'<hr>';
    $html='';
     if(!empty($products))
    {
        if(empty($prodid))$prodid=$products[0]->id;
            foreach($products as $p){
               $html.= ' <a  '.($p->id===$prodid?'':' class="text-muted" ').' href="#">'.$p->ref.'<i class="fa fa-dropbox fa-2x" ></i>';
               $html.= '<span class="badge  badge-dark">'.$p->stock.'</span>';
               $html.= '</a>&nbsp;&nbsp;';
              }
        
    }
    $sql="SELECT  pl.rowid as id,pl.batch, pl.eatby , sum(m.value) as stock,pl.fk_product";
    $sql.=" FROM  llx_product_lot as pl";
    $sql.=" INNER JOIN llx_stock_mouvement m ON m.batch = pl.batch AND m.fk_product = pl.fk_product";
    $sql.=" WHERE  m.fk_entrepot = $warehouseid AND pl.entity IN ($conf->entity)  AND m.fk_product=$prodid";
    $sql.=" GROUP BY pl.rowid,pl.eatby";
    $sql.=" ORDER BY pl.rowid,pl.eatby DESC";
    //print $sql;
    $batchs = $context->dbTool->executeS($sql);
    print '<p class="h5">'.$langs->trans('SelectBatch').'</p>';
     print '<p class="h6 text-muted">'.$langs->trans('For').': '.$soc->name.'</p>';
    print $db->lasterror;
    $html.= '<hr>
             <a name="list">
            <div class="input-group md-form form-sm form-1 pl-0">
                <div class="input-group-prepend">
                    <span class="input-group-text cyan lighten-2" id="basic-text1">
                    <i class="fa fa-search text-white" aria-hidden="true"></i></span>
                </div>
                <input class="form-control my-0 py-1" type="text" placeholder="Search" aria-label="Search">
                </div><br>
                <div class="list-group">';
                 
    if(!empty($batchs)){
        foreach($batchs as $b){
            //var_dump($b->stock);
            if($b->stock==1){
                  $data='&'.http_build_query(array(
                   'step'=>2,
                   'socid'=>$soc->id,
                   'batch'=>$b->batch,
                   'batchid'=>$b->id,
                   'eatby'=>$b->eatby,
                   'fk_product'=>$b->fk_product
                  )                   
                  );
                  $link=$context->getRootUrl('costumerorder',$data);
                  $isselected=' href="'.$link.'" class="list-group-item list-group-item-action';
                if(in_array($b->batch,array_keys($lines))!==false)$isselected.=' active"';
                else $isselected.=' "';
                
                $html.="<a $isselected>";
                $html.=$b->batch.'&nbsp;&nbsp<i class="fa fa-calendar">'.$b->expire.'</i><span class="badge badge-success">'.days_now($b->eatby).' dias</span>';
                $html.='        </a>';
            }
        }
    }
    $html.='</div>';
   
if(count($lines)>0){
	$html.= '<a class="btn btn-primary pull-right" href="'.$context->getRootUrl('costumerorder','&step=3').'" >'.$langs->trans('Next').'</button>';    
   
}else{
    $html.= '<p>'.$langs->trans('AddAnyLine').'</p>';
}
 $html.= '<a class="btn btn-secondary" href="'.$context->getRootUrl('costumerorder','&step=1').'"  >'.$langs->trans('Back').'</a>';

return $html;
}
function days_now( $date  )
{    
    return floor((abs(dol_now() - strtotime($date))/(60*60*24)));; 
}
function print_viewcostumerorder($id=0){
     global $langs, $db, $conf;
    $context = Context::getInstance();    
    dol_include_once('commande/class/commande.class.php');    
    $langs->load('company');
     $langs->load('commande');
    $order=new Commande($db);
    $order->fetch($id);
    $order->fetch_thirdparty();
    $html= 
     '<div class="card" >
  <div class="card-body">
    <h5 class="card-title">'.$langs->trans('Ref.').': '.$order->ref.'</h5>
    <h6 class="card-subtitle mb-2 text-muted">'.$langs->trans('For').': '.$order->thirdparty->name.'</h6>
    <h6 class="card-subtitle mb-2 small">'.$langs->trans('At').': '.dol_print_date($order->date).'</h6>';
    //<p class="card-text">';    
     $html.='<table id="ordertable" class="table card-table table-responsive-sm">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">'.$langs->trans('Description').'</th>
      <th scope="col">'.$langs->trans('Price').'</th>
    </tr>
  </thead>
  <tbody>';
   $i=0;
   $nl=urlencode("\n");
   $text=$langs->trans('YourOrder').': '.$order->ref;
   $sep=$nl.str_repeat('_ ',strlen($text)).$nl;
   $text.=$sep;
    foreach($order->lines as $l){
        $text.=$l->desc.$nl;
       $html.='  <tr>';
       $html.='<th scope="row">'.($i++).'</th>';
       $html.='<td>';
       $html.=$l->desc;
       $html.='</td>';
       $html.='<td>';
        $html.=$l->desc;
        $html.='</td>';
       $html.='</tr>';
    }
    $text.=$sep;
    $text.=price($order->total_ttc);
     $html.='</tbody></table>';
     
     // $html.='</p>';
      $html.='</div></div>';
    if(count($order->lines)>0){
        $html.='<script type="text/javascript" src="'.dol_buildpath('streamaccount/inc/jquery-ascii/jquery.ascii.min.js',1).'"></script>';
        $html.='<script>
        $(document).ready(function() {
        //var body=$.param( {body:$("#ordertable").ascii()});
        var body=$.param( {body:'.$text.'});
            var href="sms://+57'.$order->thirdparty->phone.'?&"+body;
           // href+="?&body=xxxxxx";
            $("#chanel").attr("href",href);
            //$("#chanel").click(function(e){e.preventDefault();window.location.href = href;});
        });    
        </script>';
        $html.= '<p>'.$langs->trans('SendBy').'</p>';
        $html.= '<a class="m-1 btn btn-primary  pull-right" href="'.$context->getRootUrl('costumerorder','&action=pre_send&id='.$id).'" value="1" ><i class="fa fa-facebook"></i></a>';    
        $html.= '<a class="m-1 btn btn-primary  pull-right" href="'.$context->getRootUrl('costumerorder','&action=pre_send&id='.$id).'" value="1" ><i class="fa fa-whatsapp"></i></a>';
        $html.= '<a class="m-1 btn btn-primary  pull-right" href="'.$context->getRootUrl('costumerorder','&action=pre_send&id='.$id).'" value="1" ><i class="fa fa-comment"></i></a>';    
   
}else{
    $html.= '<p>'.$langs->trans('AddAnyLine').'</p>';
}
 $html.= '<a id="chanel" class="btn btn-secondary" href="sms://'.$order->thirdparty->phone.'?&body='.($text).'"  >'.$langs->trans('SendBy').'</a>';
 

return $html;
}
function confirm_costumerorder($socid=0,$lines=array()){
     global $langs, $db, $conf;
    $context = Context::getInstance();    
    dol_include_once('compta/societe/class/societe.class.php');    
    $langs->load('company');
    $soc=new Societe($db);
    $soc->fetch($socid);
     $html.='';
    if(!isMobile())
    $html.='<div class="card">
  <div class="card-body">';
    $html.='<h5 class="card-title">'.$langs->trans('OrderOK').'</h5>
    <h6 class="card-subtitle mb-2 text-muted">'.$langs->trans('For').': '.$soc->name.'</h6>';
    //<p class="card-text">';    
     $html.='<table width="100%" class="table card-table table-responsive-sm">
  <thead>
    <tr>';
     if(!isMobile())
      $html.=' <th scope="col" ">#</th>';
      $html.=' <th  id="tdbatch"  scope="col">'.$langs->trans('Description').'</th>
      <th id="tdprice" scope="col">'.$langs->trans('Price').'</th>
    </tr>
  </thead>
  <tbody>';
   $i=0;
    foreach($lines as $l){
       $html.='  <tr>';
       if(!isMobile())
       $html.='<th style="text-overflow:hidden;" scope="row">'.($i++).'</th>';
       $html.='<td class="'.(isMobile()?'small':'').'">'.$l['batch'];
       $html.='</td>';
       $html.='<td><input class=".form-control" type="number" name="lines['.$l['batch'].'][subprice]" step="1" style="width: 5em;" required pattern="\d+" title="YOUR_WARNING_TEXT">';
        $html.='<input type="hidden" value="'.$l['batch'].'" name="lines['.$l['batch'].'][batch]">';
       $html.='<input type="hidden" value="'.$l['batchid'].'" name="lines['.$l['batch'].'][origin_id]">';
       $html.='<input type="hidden" value="account:'.$l['batchid'].':'.$l['batch'].':'.$l['eatby'].'" name="lines['.$l['batch'].'][label]">';
       $html.='<input type="hidden" value="productlot" name="lines['.$l['batch'].'][origin]">';
       $html.='<input type="hidden" value="'.$l['fk_product'].'" name="lines['.$l['batch'].'][fk_product]">';
       $html.='<input type="hidden" value="1" name="lines['.$l['batch'].'][qty]">';
      $html.='</td>';
       $html.='</tr>';
    }
     $html.='</tbody></table>';
    
     // $html.='</p>';
     if(!isMobile());
      $html.='</div></div>';
      $html.="\n<script>";
      $html.='jQuery.fn.hasHScrollBar = function()
        {
          // log(this.get(0).scrollWidth);
          // log(this.width());
          // log(this.innerWidth());
            return this.get(0).scrollWidth > this.innerWidth();
        };
        $("table").hasHScrollBar();
        alert("horisontal?: "+ $("table").hasHScrollBar());
        var priceFocus=false;
        $("table").on("gesture-down", function (e) { alert();});
        $("table").scroll(function () {
            if(!priceFocus){
                    $("#tdprice").focus();
                    priceFocus=true;
                }else{
                    $("#tdbatch").focus();
                    priceFocus=false;
                };
                console.log("price focus:",priceFocus);
        });';
  
      $html.="\n</script>";
      if(count($lines)>0){
	$html.= '<button class="btn btn-primary pull-right" type="submit" name="save" value="1" >'.$langs->trans('Save').'</button>';    
   
}else{
    $html.= '<p>'.$langs->trans('AddAnyLine').'</p>';
}
 $html.= '<a class="btn btn-secondary" href="'.$context->getRootUrl('costumerorder','&step=2').'"  >'.$langs->trans('Back').'</a>';

return $html;
}
function exception_to_msg($excepción) {
		echo "Excepción no capturada: " , $excepción->getMessage(), "\n";
	}
function isMobile() {
    return preg_match("/(android|avantgo|blackberry|bolt|boost|cricket|docomo|fone|hiptop|mini|mobi|palm|phone|pie|tablet|up\.browser|up\.link|webos|wos)/i", $_SERVER["HTTP_USER_AGENT"]);
}